import type { MisskeyTheme } from './types'

export const DARK_THEME: MisskeyTheme = {
  id: 'builtin-dark',
  name: 'Dark',
  base: 'dark',
  props: {
    accent: '#86b300',
    accentedBg: ':alpha<0.15<@accent',
    love: '#dd2e44',
    focus: ':alpha<0.3<@accent',
    bg: '#232323',
    fg: 'rgb(199, 209, 216)',
    fgHighlighted: '#fff',
    fgOnAccent: '#fff',
    fgOnWhite: '#333',
    divider: 'rgba(255, 255, 255, 0.14)',
    indicator: '@accent',
    panel: '#2d2d2d',
    panelHighlight: ':lighten<3<@panel',
    panelHeaderBg: ':lighten<3<@panel',
    panelHeaderFg: '@fg',
    panelBorder: '" solid 1px var(--MI_THEME-divider)',
    windowHeader: ':alpha<0.85<@panel',
    popup: ':lighten<3<@panel',
    shadow: 'rgba(0, 0, 0, 0.3)',
    header: ':alpha<0.7<@panel',
    navBg: '#363636',
    navFg: '@fg',
    navActive: '@accent',
    navIndicator: '@indicator',
    pageHeaderBg: '@bg',
    pageHeaderFg: '@fg',
    link: '@accent',
    hashtag: '#4cb8d4',
    mention: '#da6d35',
    mentionMe: '#d44c4c',
    renote: '@accent',
    modalBg: 'rgba(0, 0, 0, 0.5)',
    scrollbarHandle: 'rgba(255, 255, 255, 0.2)',
    scrollbarHandleHover: 'rgba(255, 255, 255, 0.4)',
    dateLabelFg: '@fg',
    infoBg: '#253142',
    infoFg: '#fff',
    infoWarnBg: '#42321c',
    infoWarnFg: '#ffbd3e',
    folderHeaderBg: 'rgba(255, 255, 255, 0.05)',
    folderHeaderHoverBg: 'rgba(255, 255, 255, 0.1)',
    buttonBg: ':lighten<5<@panel',
    buttonHoverBg: ':lighten<10<@panel',
    buttonGradateA: '@accent',
    buttonGradateB: ':hue<20<@accent',
    switchBg: 'rgba(255, 255, 255, 0.15)',
    switchOffBg: 'rgba(255, 255, 255, 0.1)',
    switchOffFg: ':alpha<0.8<@fg',
    switchOnBg: '@accentedBg',
    switchOnFg: '@accent',
    inputBorder: 'rgba(255, 255, 255, 0.1)',
    inputBorderHover: 'rgba(255, 255, 255, 0.2)',
    badge: '#31b1ce',
    messageBg: '@bg',
    success: '#86b300',
    error: '#ec4137',
    warn: '#ecb637',
    codeString: '#ffb675',
    codeNumber: '#cfff9e',
    codeBoolean: '#c59eff',
    deckBg: '#1a1a1a',
    htmlThemeColor: '@bg',
  },
}

export const LIGHT_THEME: MisskeyTheme = {
  id: 'builtin-light',
  name: 'Light',
  base: 'light',
  props: {
    accent: '#86b300',
    accentedBg: ':alpha<0.15<@accent',
    love: '#dd2e44',
    focus: ':alpha<0.3<@accent',
    bg: '#f9f9f9',
    fg: '#676767',
    fgHighlighted: ':darken<3<@fg',
    fgOnAccent: '#fff',
    fgOnWhite: '#333',
    divider: '#e8e8e8',
    indicator: '@accent',
    panel: '#fff',
    panelHighlight: ':darken<3<@panel',
    panelHeaderBg: ':lighten<3<@panel',
    panelHeaderFg: '@fg',
    panelBorder: '" solid 1px var(--MI_THEME-divider)',
    windowHeader: ':alpha<0.85<@panel',
    popup: ':lighten<3<@panel',
    shadow: 'rgba(0, 0, 0, 0.1)',
    header: ':alpha<0.7<@panel',
    navBg: '#fff',
    navFg: '@fg',
    navActive: '@accent',
    navIndicator: '@indicator',
    pageHeaderBg: '@bg',
    pageHeaderFg: '@fg',
    link: '@accent',
    hashtag: '#4cb8d4',
    mention: '@accent',
    mentionMe: 'rgb(0, 179, 70)',
    renote: '@accent',
    modalBg: 'rgba(0, 0, 0, 0.3)',
    scrollbarHandle: 'rgba(0, 0, 0, 0.2)',
    scrollbarHandleHover: 'rgba(0, 0, 0, 0.4)',
    dateLabelFg: '@fg',
    infoBg: '#e5f5ff',
    infoFg: '#72818a',
    infoWarnBg: '#fff0db',
    infoWarnFg: '#8f6e31',
    folderHeaderBg: 'rgba(0, 0, 0, 0.05)',
    folderHeaderHoverBg: 'rgba(0, 0, 0, 0.1)',
    buttonBg: ':darken<5<@panel',
    buttonHoverBg: ':darken<10<@panel',
    buttonGradateA: '@accent',
    buttonGradateB: ':hue<20<@accent',
    switchBg: 'rgba(0, 0, 0, 0.15)',
    switchOffBg: 'rgba(0, 0, 0, 0.1)',
    switchOffFg: '@panel',
    switchOnBg: '@accent',
    switchOnFg: '@fgOnAccent',
    inputBorder: 'rgba(0, 0, 0, 0.1)',
    inputBorderHover: 'rgba(0, 0, 0, 0.2)',
    badge: '#31b1ce',
    messageBg: '@bg',
    success: '#86b300',
    error: '#ec4137',
    warn: '#ecb637',
    codeString: '#b98710',
    codeNumber: '#0fbbbb',
    codeBoolean: '#62b70c',
    deckBg: ':darken<3<@bg',
    htmlThemeColor: '@bg',
  },
}
