<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, useCssModule, watch } from 'vue'
import { useColumnTheme } from '@/composables/useColumnTheme'
import type { DeckColumn as DeckColumnType } from '@/stores/deck'
import { useThemeStore } from '@/stores/theme'
import DeckColumn from './DeckColumn.vue'

const props = defineProps<{
  column: DeckColumnType
}>()

const { columnThemeVars } = useColumnTheme(() => props.column)
const themeStore = useThemeStore()

const tab = ref<'presets' | 'code'>('presets')

// Local CSS mirror (synced from store on mount)
const cssCode = ref(themeStore.customCss)

// Preset toggles
const presets = ref({
  customFont: '',
  fontSize: 0, // 0 = default, otherwise px offset from 15px base
})

// Parse existing CSS to restore preset states
function parsePresetsFromCss(css: string) {
  const fontMatch = css.match(/\/\* nd-font: (.+?) \*\//)
  presets.value.customFont = fontMatch?.[1] ?? ''
  const sizeMatch = css.match(/\/\* nd-fontsize: (.+?) \*\//)
  presets.value.fontSize = sizeMatch ? Number(sizeMatch[1]) : 0
}
parsePresetsFromCss(cssCode.value)

interface FontOption {
  value: string
  label: string
  importUrl?: string
  customCss?: string
}

const FONT_OPTIONS: FontOption[] = [
  { value: '', label: 'デフォルト' },
  { value: 'Noto Sans JP', label: 'Noto Sans JP' },
  { value: 'Noto Serif JP', label: 'Noto Serif JP' },
  { value: 'Sawarabi Gothic', label: 'Sawarabi Gothic' },
  { value: 'Sawarabi Mincho', label: 'Sawarabi Mincho' },
  { value: 'M PLUS 1p', label: 'M PLUS' },
  { value: 'M PLUS Rounded 1c', label: 'M PLUS Rounded' },
  { value: 'M PLUS 2', label: 'M PLUS 2' },
  { value: 'Murecho', label: 'Murecho' },
  { value: 'RocknRoll One', label: 'RocknRoll One' },
  { value: 'Klee One', label: 'Klee One' },
  { value: 'Zen Maru Gothic', label: 'Zen Maru Gothic' },
  { value: 'Kaisei Decol', label: 'Kaisei Decol' },
  { value: 'Yomogi', label: 'Yomogi' },
  { value: 'Kosugi', label: 'Kosugi' },
  { value: 'Kosugi Maru', label: 'Kosugi Maru' },
  {
    value: 'Kiwi Maru',
    label: 'Kiwi Maru',
    importUrl:
      'https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap',
  },
  { value: 'Hachi Maru Pop', label: 'Hachi Maru Pop' },
  { value: 'Mochiy Pop One', label: 'Mochiy Pop One' },
  { value: 'Mochiy Pop P One', label: 'Mochiy Pop P One' },
  { value: 'Yusei Magic', label: 'Yusei Magic' },
  { value: 'DotGothic16', label: 'Dot Gothic 16' },
  {
    value: '手書き雑フォント',
    label: '手書き雑フォント',
    customCss: `@font-face { font-family: '手書き雑フォント'; src: url('https://cdn.leafscape.be/tegaki_zatsu/851tegaki_zatsu_web.woff2') format("woff2"); font-display: swap; }`,
  },
  {
    value: '瀬戸フォント',
    label: '瀬戸フォント',
    customCss: `@font-face { font-family: '瀬戸フォント'; src: url('https://cdn.leafscape.be/setofont/setofont_web.woff2') format("woff2"); font-display: swap; }`,
  },
]

const FONT_SIZE_BASE = 15
const FONT_SIZE_MIN = -3
const FONT_SIZE_MAX = 5

const fontSizeLabel = computed(() => {
  if (presets.value.fontSize === 0) return 'デフォルト (15px)'
  return `${FONT_SIZE_BASE + presets.value.fontSize}px`
})

// Validate CSS by attempting to parse it with CSSStyleSheet
function validateCss(css: string): string | null {
  if (!css.trim()) return null
  // Strip @import and @font-face blocks (not supported by CSSStyleSheet.replaceSync)
  const testCss = css
    .split('\n')
    .filter((line) => {
      const t = line.trim()
      return !t.startsWith('@import') && !t.startsWith('@font-face')
    })
    .join('\n')
  try {
    const sheet = new CSSStyleSheet()
    sheet.replaceSync(testCss)
    return null
  } catch (e) {
    return e instanceof Error ? e.message : 'CSSパースエラー'
  }
}

// Build CSS from presets (always valid, no validation needed)
function buildPresetCss(): string {
  const parts: string[] = []

  if (presets.value.customFont) {
    const font = presets.value.customFont
    const opt = FONT_OPTIONS.find((o) => o.value === font)
    parts.push(`/* nd-font: ${font} */`)
    if (opt?.customCss) {
      parts.push(opt.customCss)
    } else {
      const url =
        opt?.importUrl ??
        `https://fonts.googleapis.com/css2?family=${encodeURIComponent(font)}&display=swap`
      parts.push(`@import url('${url}');`)
    }
    parts.push(`html { font-family: '${font}', sans-serif; }`)
  }

  if (presets.value.fontSize !== 0) {
    const px = FONT_SIZE_BASE + presets.value.fontSize
    parts.push(`/* nd-fontsize: ${presets.value.fontSize} */`)
    parts.push(`html { font-size: ${px}px; }`)
  }

  return parts.join('\n')
}

// Extract user's freeform CSS (lines not generated by presets)
function extractUserCss(fullCss: string): string {
  return fullCss
    .split('\n')
    .filter((line) => {
      const t = line.trim()
      if (!t) return false
      if (t.startsWith('/* nd-font:')) return false
      if (t.startsWith('/* nd-fontsize:')) return false
      if (t.startsWith('@import url(')) return false
      if (t.startsWith('@font-face')) return false
      if (t.match(/^html\s*\{\s*font-family:/)) return false
      if (t.match(/^html\s*\{\s*font-size:/)) return false
      return true
    })
    .join('\n')
    .trim()
}

const userFreeformCss = ref(extractUserCss(cssCode.value))
const cssError = ref<string | null>(null)

// Validate freeform CSS on change (debounced)
let validateTimer: ReturnType<typeof setTimeout> | null = null
watch(userFreeformCss, (css) => {
  if (validateTimer) clearTimeout(validateTimer)
  validateTimer = setTimeout(() => {
    cssError.value = validateCss(css)
  }, 300)
})

// Combine preset + validated user CSS
const fullCss = computed(() => {
  const preset = buildPresetCss()
  const user = cssError.value ? '' : userFreeformCss.value.trim()
  if (preset && user) return `${preset}\n\n${user}`
  return preset || user
})

// Apply on change (debounced)
let applyTimer: ReturnType<typeof setTimeout> | null = null
watch(fullCss, (css) => {
  cssCode.value = css
  if (applyTimer) clearTimeout(applyTimer)
  applyTimer = setTimeout(() => {
    themeStore.setCustomCss(css)
  }, 200)
})

// Preset changes apply immediately (safe, no validation needed)
watch(
  () => [presets.value.customFont, presets.value.fontSize],
  () => {
    const css = fullCss.value
    cssCode.value = css
    themeStore.setCustomCss(css)
  },
)

// Code tab: debounced live preview
const codeError = ref<string | null>(null)
let codeApplyTimer: ReturnType<typeof setTimeout> | null = null

watch(cssCode, (css) => {
  if (tab.value !== 'code') return
  if (codeApplyTimer) clearTimeout(codeApplyTimer)
  codeApplyTimer = setTimeout(() => {
    const err = validateCss(css)
    codeError.value = err
    if (!err) {
      themeStore.setCustomCss(css)
    }
  }, 400)
})

function applyFromCode() {
  if (codeApplyTimer) clearTimeout(codeApplyTimer)
  const css = cssCode.value
  const err = validateCss(css)
  if (err) {
    codeError.value = err
    return
  }
  codeError.value = null
  parsePresetsFromCss(css)
  userFreeformCss.value = extractUserCss(css)
  cssError.value = null
  themeStore.setCustomCss(css)
}

// Clear all with confirmation
const confirmingClear = ref(false)
let clearTimer: ReturnType<typeof setTimeout> | null = null

function handleClear() {
  if (confirmingClear.value) {
    if (clearTimer) clearTimeout(clearTimer)
    confirmingClear.value = false
    presets.value = { customFont: '', fontSize: 0 }
    userFreeformCss.value = ''
    cssCode.value = ''
    cssError.value = null
    codeError.value = null
    themeStore.setCustomCss('')
  } else {
    confirmingClear.value = true
    clearTimer = setTimeout(() => {
      confirmingClear.value = false
    }, 3000)
  }
}

// Font dropdown
const showFontDropdown = ref(false)
const cssModule = useCssModule()

const selectedFontLabel = computed(() => {
  const opt = FONT_OPTIONS.find((o) => o.value === presets.value.customFont)
  return opt?.label ?? 'デフォルト'
})

function selectFont(value: string) {
  presets.value.customFont = value
  showFontDropdown.value = false
}

// Close dropdown on outside click
function handleOutsideClick(e: MouseEvent) {
  const target = e.target as HTMLElement
  if (!target.closest(`.${cssModule.dropdown}`)) {
    showFontDropdown.value = false
  }
}

onMounted(() => document.addEventListener('click', handleOutsideClick))
onUnmounted(() => document.removeEventListener('click', handleOutsideClick))

// Sync code tab when switching
watch(tab, (t) => {
  if (t === 'code') {
    cssCode.value = fullCss.value
    codeError.value = null
  } else {
    // Switching back to presets: sync state from code
    parsePresetsFromCss(cssCode.value)
    userFreeformCss.value = extractUserCss(cssCode.value)
  }
})
</script>

<template>
  <DeckColumn
    :column-id="column.id"
    :title="column.name ?? 'カスタムCSS'"
    :theme-vars="columnThemeVars"
  >
    <template #header-icon>
      <i class="ti ti-code" :class="$style.headerIcon" />
    </template>

    <div :class="$style.editor">
      <!-- Tabs -->
      <div :class="$style.tabs">
        <button
          class="_button"
          :class="[$style.tab, { [$style.active]: tab === 'presets' }]"
          @click="tab = 'presets'"
        >
          <i class="ti ti-adjustments" />
          プリセット
        </button>
        <button
          class="_button"
          :class="[$style.tab, { [$style.active]: tab === 'code' }]"
          @click="tab = 'code'"
        >
          <i class="ti ti-code" />
          コード
        </button>
      </div>

      <!-- Presets -->
      <div v-show="tab === 'presets'" :class="$style.presetsPanel">
        <!-- Font -->
        <div :class="$style.section">
          <div :class="$style.sectionLabel">
            <i class="ti ti-typography" />
            フォント
          </div>
          <div :class="$style.dropdown">
            <button
              class="_button"
              :class="$style.dropdownTrigger"
              @click="showFontDropdown = !showFontDropdown"
            >
              <span
                v-if="presets.customFont"
                :class="$style.fontPreviewLabel"
                :style="{ fontFamily: `'${presets.customFont}', sans-serif` }"
              >{{ selectedFontLabel }}</span>
              <span v-else>{{ selectedFontLabel }}</span>
              <i class="ti ti-chevron-down" :class="$style.dropdownChevron" />
            </button>
            <div v-if="showFontDropdown" :class="$style.dropdownPanel">
              <button
                v-for="opt in FONT_OPTIONS"
                :key="opt.value"
                class="_button"
                :class="[$style.dropdownItem, { [$style.selected]: presets.customFont === opt.value }]"
                @click="selectFont(opt.value)"
              >
                <span
                  v-if="opt.value"
                  :class="$style.fontPreviewLabel"
                  :style="{ fontFamily: `'${opt.value}', sans-serif` }"
                >{{ opt.label }}</span>
                <span v-else>{{ opt.label }}</span>
                <i v-if="presets.customFont === opt.value" class="ti ti-check" :class="$style.checkIcon" />
              </button>
            </div>
          </div>
          <div v-if="presets.customFont" :class="$style.preview" :style="{ fontFamily: `'${presets.customFont}', sans-serif` }">
            あいうえお ABCabc 123
          </div>
        </div>

        <!-- Font Size -->
        <div :class="$style.section">
          <div :class="$style.sectionLabel">
            <i class="ti ti-text-resize" />
            フォントサイズ
            <span :class="$style.sectionValue">{{ fontSizeLabel }}</span>
          </div>
          <div :class="$style.sliderRow">
            <span :class="$style.sliderLabel">小</span>
            <input
              v-model.number="presets.fontSize"
              type="range"
              :min="FONT_SIZE_MIN"
              :max="FONT_SIZE_MAX"
              step="1"
              :class="$style.slider"
            />
            <span :class="$style.sliderLabel">大</span>
          </div>
          <button
            v-if="presets.fontSize !== 0"
            class="_button"
            :class="$style.resetBtn"
            @click="presets.fontSize = 0"
          >
            リセット
          </button>
        </div>

        <!-- Freeform CSS -->
        <div :class="$style.section">
          <div :class="$style.sectionLabel">
            <i class="ti ti-pencil" />
            追加CSS
          </div>
          <textarea
            v-model="userFreeformCss"
            :class="[$style.textarea, { [$style.hasError]: cssError }]"
            placeholder="自由にCSSを記述..."
            spellcheck="false"
            rows="10"
          />
          <div v-if="cssError" :class="$style.errorMessage">
            <i class="ti ti-alert-triangle" />
            {{ cssError }}
          </div>
          <div v-if="cssError" :class="$style.errorHint">
            CSSにエラーがあるため適用されません
          </div>
        </div>
      </div>

      <!-- Code Editor -->
      <div v-show="tab === 'code'" :class="$style.codePanel">
        <div :class="$style.codeHint">
          プリセットと追加CSSを結合した全体のCSSです
        </div>
        <textarea
          v-model="cssCode"
          :class="[$style.codeTextarea, { [$style.hasError]: codeError }]"
          spellcheck="false"
          rows="20"
        />
        <div v-if="codeError" :class="$style.errorMessage">
          <i class="ti ti-alert-triangle" />
          {{ codeError }}
        </div>
        <div v-if="!codeError && cssCode.trim()" :class="$style.codeSuccess">
          <i class="ti ti-check" />
          適用中
        </div>
        <button
          class="_button"
          :class="$style.codeApplyBtn"
          @click="applyFromCode"
        >
          <i class="ti ti-refresh" />
          プリセットに同期
        </button>
      </div>

      <!-- Actions -->
      <div :class="$style.actions">
        <button
          class="_button"
          :class="[$style.actionBtn, $style.danger, { [$style.confirming]: confirmingClear }]"
          @click="handleClear"
        >
          <i class="ti ti-trash" />
          {{ confirmingClear ? '本当にクリア？' : 'すべてクリア' }}
        </button>
      </div>
    </div>
  </DeckColumn>
</template>

<style lang="scss" module>
.headerIcon {
  flex-shrink: 0;
  opacity: 0.7;
}

.editor {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
  overflow: hidden;
}

.tabs {
  display: flex;
  gap: 0;
  border-bottom: 1px solid var(--nd-divider);
  flex-shrink: 0;
}

.tab {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 6px 12px;
  font-size: 0.75em;
  font-weight: bold;
  color: var(--nd-fg);
  opacity: 0.5;
  border-bottom: 2px solid transparent;
  transition: opacity var(--nd-duration-base), border-color var(--nd-duration-base);

  &:hover {
    opacity: 0.8;
  }

  &.active {
    opacity: 1;
    border-bottom-color: var(--nd-accent);
    color: var(--nd-accent);
  }
}

.active {
  /* modifier */
}

.hasError {
  /* modifier */
}

.confirming {
  /* modifier */
}

.presetsPanel {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
  overflow-y: auto;
}

.section {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 12px 10px;
  border-bottom: 1px solid var(--nd-divider);
}

.sectionLabel {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.8em;
  font-weight: bold;
  opacity: 0.7;
}

.sectionValue {
  margin-left: auto;
  font-weight: normal;
  font-size: 0.9em;
  opacity: 0.8;
}

.dropdown {
  position: relative;
  width: 100%;
}

.dropdownTrigger {
  display: flex;
  align-items: center;
  gap: 6px;
  width: 100%;
  padding: 6px 10px;
  border: 1px solid var(--nd-divider);
  border-radius: var(--nd-radius-sm);
  background: var(--nd-bg);
  color: var(--nd-fg);
  font-size: 0.8em;
  text-align: left;
  transition: border-color var(--nd-duration-base), background var(--nd-duration-base);

  &:hover {
    background: var(--nd-buttonHoverBg);
  }
}

.dropdownChevron {
  margin-left: auto;
  opacity: 0.4;
  font-size: 0.85em;
}

.dropdownPanel {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  z-index: 100;
  max-height: 240px;
  overflow-y: auto;
  margin-top: 2px;
  border: 1px solid var(--nd-divider);
  border-radius: var(--nd-radius-sm);
  background: var(--nd-panel);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.25);
}

.dropdownItem {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 7px 10px;
  font-size: 0.8em;
  color: var(--nd-fg);
  text-align: left;
  cursor: pointer;
  transition: background var(--nd-duration-base);

  &:hover {
    background: var(--nd-buttonHoverBg);
  }

  &.selected {
    color: var(--nd-accent);
  }

  & + & {
    border-top: 1px solid color-mix(in srgb, var(--nd-divider) 50%, transparent);
  }
}

.selected {
  /* modifier */
}

.fontPreviewLabel {
  flex: 1;
  min-width: 0;
}

.checkIcon {
  margin-left: auto;
  opacity: 0.7;
  flex-shrink: 0;
}

.preview {
  padding: 8px 10px;
  border-radius: var(--nd-radius-sm);
  background: var(--nd-bg);
  font-size: 0.9em;
  text-align: center;
}

.sliderRow {
  display: flex;
  align-items: center;
  gap: 8px;
}

.sliderLabel {
  font-size: 0.7em;
  opacity: 0.5;
  flex-shrink: 0;
}

.slider {
  flex: 1;
  height: 4px;
  appearance: none;
  background: var(--nd-divider);
  border-radius: 2px;
  outline: none;
  cursor: pointer;

  &::-webkit-slider-thumb {
    appearance: none;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background: var(--nd-accent);
    cursor: pointer;
  }

  &::-moz-range-thumb {
    width: 16px;
    height: 16px;
    border: none;
    border-radius: 50%;
    background: var(--nd-accent);
    cursor: pointer;
  }
}

.resetBtn {
  align-self: flex-end;
  padding: 2px 8px;
  border-radius: var(--nd-radius-sm);
  background: var(--nd-buttonBg);
  color: var(--nd-fg);
  font-size: 0.7em;
  opacity: 0.6;
  transition: opacity var(--nd-duration-base), background var(--nd-duration-base);

  &:hover {
    opacity: 1;
    background: var(--nd-buttonHoverBg);
  }
}

.textarea {
  padding: 8px 10px;
  border: 1px solid var(--nd-divider);
  border-radius: var(--nd-radius-sm);
  background: var(--nd-bg);
  color: var(--nd-fg);
  font-family: 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
  font-size: 0.75em;
  line-height: 1.5;
  resize: vertical;
  outline: none;
  transition: border-color var(--nd-duration-base);

  &:focus {
    border-color: var(--nd-accent);
  }

  &.hasError {
    border-color: var(--nd-love);
  }
}

.errorMessage {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 6px 8px;
  border-radius: var(--nd-radius-sm);
  background: color-mix(in srgb, var(--nd-love) 10%, var(--nd-bg));
  color: var(--nd-love);
  font-size: 0.75em;
  word-break: break-all;
}

.errorHint {
  font-size: 0.7em;
  opacity: 0.5;
}

.codePanel {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 10px;
  flex: 1;
  min-height: 0;
  overflow-y: auto;
}

.codeHint {
  font-size: 0.75em;
  opacity: 0.4;
}

.codeTextarea {
  flex: 1;
  min-height: 200px;
  padding: 8px 10px;
  border: 1px solid var(--nd-divider);
  border-radius: var(--nd-radius-sm);
  background: var(--nd-bg);
  color: var(--nd-fg);
  font-family: 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
  font-size: 0.75em;
  line-height: 1.5;
  resize: vertical;
  outline: none;
  transition: border-color var(--nd-duration-base);

  &:focus {
    border-color: var(--nd-accent);
  }

  &.hasError {
    border-color: var(--nd-love);
  }
}

.codeSuccess {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 0.75em;
  color: var(--nd-accent);
  opacity: 0.7;
}

.codeApplyBtn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 6px 12px;
  border-radius: var(--nd-radius-sm);
  background: var(--nd-buttonBg);
  color: var(--nd-fg);
  font-size: 0.8em;
  font-weight: bold;
  transition: background var(--nd-duration-base);

  &:hover {
    background: var(--nd-buttonHoverBg);
  }
}

.actions {
  display: flex;
  gap: 6px;
  padding: 10px;
  border-top: 1px solid var(--nd-divider);
  flex-shrink: 0;
}

.actionBtn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 4px;
  flex: 1;
  padding: 8px 12px;
  border-radius: var(--nd-radius-sm);
  font-size: 0.8em;
  font-weight: bold;
  transition: background var(--nd-duration-base), color var(--nd-duration-base);

  &.danger {
    background: var(--nd-buttonBg);
    color: var(--nd-fg);

    &:hover {
      background: color-mix(in srgb, var(--nd-love) 20%, var(--nd-buttonBg));
      color: var(--nd-love);
    }

    &.confirming {
      background: color-mix(in srgb, var(--nd-love) 30%, var(--nd-buttonBg));
      color: var(--nd-love);
    }
  }
}

.danger {
  /* modifier */
}
</style>
