
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadAccounts() : Promise<Result<AccountPublic[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAccount(id: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logout: delete token only, keep account record and columns
 */
async logoutAccount(id: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a guest (unauthenticated) account for browsing public timelines.
 */
async createGuestAccount(host: string, software: string) : Promise<Result<AccountPublic, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_guest_account", { host, software }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cacheStats() : Promise<Result<CacheStats, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async accountCacheCount(accountId: string) : Promise<Result<number, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("account_cache_count", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAccountCache(accountId: string) : Promise<Result<number, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_account_cache", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllCache() : Promise<Result<number, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadServers() : Promise<Result<StoredServer[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServer(host: string) : Promise<Result<StoredServer | null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertServer(server: StoredServer) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_server", { server }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetEndpoints(host: string) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_endpoints", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetEndpointParams(host: string, endpoint: string) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_endpoint_params", { host, endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserPolicies(accountId: string) : Promise<Result<Partial<{ [key in string]: boolean }>, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_policies", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUpdateUserSetting(accountId: string, key: string, value: boolean) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_update_user_setting", { accountId, key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetTimeline(accountId: string, timelineType: TimelineType, options: TimelineOptions | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_timeline", { accountId, timelineType, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserLists(accountId: string) : Promise<Result<UserList[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_lists", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetAntennas(accountId: string) : Promise<Result<Antenna[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_antennas", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetAntennaNotes(accountId: string, antennaId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_antenna_notes", { accountId, antennaId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFavorites(accountId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_favorites", { accountId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFeaturedNotes(accountId: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_featured_notes", { accountId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetMentions(accountId: string, limit: number | null, sinceId: string | null, untilId: string | null, visibility: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_mentions", { accountId, limit, sinceId, untilId, visibility }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetClips(accountId: string) : Promise<Result<Clip[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_clips", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetClipNotes(accountId: string, clipId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_clip_notes", { accountId, clipId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetChannels(accountId: string) : Promise<Result<Channel[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_channels", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchChannels(accountId: string, query: string) : Promise<Result<Channel[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_channels", { accountId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetChannelNotes(accountId: string, channelId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_channel_notes", { accountId, channelId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetRoleNotes(accountId: string, roleId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_role_notes", { accountId, roleId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNote(accountId: string, noteId: string) : Promise<Result<NormalizedNote, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateNote(accountId: string, params: CreateNoteParams, channelId: string | null) : Promise<Result<NormalizedNote, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_note", { accountId, params, channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateReaction(accountId: string, noteId: string, reaction: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_reaction", { accountId, noteId, reaction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteReaction(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_reaction", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiVotePoll(accountId: string, noteId: string, choice: number) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_vote_poll", { accountId, noteId, choice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNoteReactions(accountId: string, noteId: string, reactionType: string | null, limit: number | null, untilId: string | null) : Promise<Result<NormalizedNoteReaction[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note_reactions", { accountId, noteId, reactionType, limit, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUpdateNote(accountId: string, noteId: string, params: CreateNoteParams) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_update_note", { accountId, noteId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUploadFile(accountId: string, fileName: string, fileData: number[], contentType: string, isSensitive: boolean, folderId: string | null) : Promise<Result<NormalizedDriveFile, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_upload_file", { accountId, fileName, fileData, contentType, isSensitive, folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUploadFileFromPath(accountId: string, filePath: string, isSensitive: boolean, folderId: string | null) : Promise<Result<NormalizedDriveFile, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_upload_file_from_path", { accountId, filePath, isSensitive, folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateFavorite(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_favorite", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteFavorite(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_favorite", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteNote(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiFollowUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_follow_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnfollowUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unfollow_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiAcceptFollowRequest(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_accept_follow_request", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiRejectFollowRequest(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_reject_follow_request", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUser(accountId: string, userId: string) : Promise<Result<NormalizedUser, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserDetail(accountId: string, userId: string) : Promise<Result<NormalizedUserDetail, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_detail", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserNotes(accountId: string, userId: string, options: TimelineOptions | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_notes", { accountId, userId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetServerEmojis(accountId: string) : Promise<Result<ServerEmoji[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_server_emojis", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetPinnedReactions(accountId: string) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_pinned_reactions", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNotifications(accountId: string, options: TimelineOptions | null) : Promise<Result<NormalizedNotification[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_notifications", { accountId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNotificationsGrouped(accountId: string, options: TimelineOptions | null) : Promise<Result<NormalizedNotification[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_notifications_grouped", { accountId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchNotes(accountId: string, query: string, options: SearchOptions | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_notes", { accountId, query, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNoteChildren(accountId: string, noteId: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note_children", { accountId, noteId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNoteRenotes(accountId: string, noteId: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note_renotes", { accountId, noteId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNoteConversation(accountId: string, noteId: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note_conversation", { accountId, noteId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiLookupUser(accountId: string, username: string, host: string | null) : Promise<Result<NormalizedUser, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_lookup_user", { accountId, username, host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetCachedTimeline(accountId: string, timelineType: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_cached_timeline", { accountId, timelineType, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteCachedNote(noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_cached_note", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bulk-verify cached notes against the server.
 * Returns a map of note_id → fresh NormalizedNote for notes that still exist.
 * Missing notes (404) are omitted from the result.
 */
async apiVerifyNotes(accountId: string, noteIds: string[]) : Promise<Result<Partial<{ [key in string]: NormalizedNote }>, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_verify_notes", { accountId, noteIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetCachedTimelineBefore(accountId: string, timelineType: string, before: string, limit: number | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_cached_timeline_before", { accountId, timelineType, before, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetCacheDateRange(accountId: string, timelineType: string) : Promise<Result<[string, string] | null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_cache_date_range", { accountId, timelineType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchNotesLocal(accountId: string, query: string, limit: number | null, sinceDate: string | null, untilDate: string | null, ascending: boolean | null) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_notes_local", { accountId, query, limit, sinceDate, untilDate, ascending }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiFindNotesByUri(uri: string) : Promise<Result<NormalizedNote[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_find_notes_by_uri", { uri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiPinNote(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_pin_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnpinNote(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unpin_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserPinnedNoteIds(accountId: string, userId: string) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_pinned_note_ids", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiMuteUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_mute_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnmuteUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unmute_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiBlockUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_block_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnblockUser(accountId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unblock_user", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiReportUser(accountId: string, userId: string, comment: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_report_user", { accountId, userId, comment }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiAddNoteToClip(accountId: string, clipId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_add_note_to_clip", { accountId, clipId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiRemoveNoteFromClip(accountId: string, clipId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_remove_note_from_clip", { accountId, clipId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiAddUserToList(accountId: string, listId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_add_user_to_list", { accountId, listId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiRemoveUserFromList(accountId: string, listId: string, userId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_remove_user_from_list", { accountId, listId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFollowing(accountId: string, userId: string, limit: number | null, untilId: string | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_following", { accountId, userId, limit, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFollowers(accountId: string, userId: string, limit: number | null, untilId: string | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_followers", { accountId, userId, limit, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserRelations(accountId: string, userIds: string[]) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_relations", { accountId, userIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUnreadNotificationCount(accountId: string) : Promise<Result<number, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_unread_notification_count", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiMarkAllNotificationsAsRead(accountId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_mark_all_notifications_as_read", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUnreadChat(accountId: string) : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_unread_chat", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetSelf(accountId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_self", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetDriveFolders(accountId: string, folderId: string | null, limit: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_drive_folders", { accountId, folderId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetDriveFiles(accountId: string, folderId: string | null, limit: number | null, fileType: string | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_drive_files", { accountId, folderId, limit, fileType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteDriveFile(accountId: string, fileId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_drive_file", { accountId, fileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFollowRequests(accountId: string, limit: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_follow_requests", { accountId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchUsers(accountId: string, query: string | null, origin: string | null, sort: string | null, state: string | null, limit: number | null, offset: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_users", { accountId, query, origin, sort, state, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetRoles(accountId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_roles", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetRoleUsers(accountId: string, roleId: string, limit: number | null, offset: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_role_users", { accountId, roleId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetAnnouncements(accountId: string, limit: number | null, isActive: boolean | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_announcements", { accountId, limit, isActive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiReadAnnouncement(accountId: string, announcementId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_read_announcement", { accountId, announcementId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiReactChatMessage(accountId: string, messageId: string, reaction: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_react_chat_message", { accountId, messageId, reaction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnreactChatMessage(accountId: string, messageId: string, reaction: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unreact_chat_message", { accountId, messageId, reaction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateMessagingMessage(accountId: string, params: JsonValue) : Promise<Result<ChatMessage, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_messaging_message", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchUsersByQuery(accountId: string, query: string, limit: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_users_by_query", { accountId, query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiSearchHashtags(accountId: string, query: string, limit: number | null) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_hashtags", { accountId, query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiApShow(accountId: string, uri: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_ap_show", { accountId, uri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetServerStats(accountId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_server_stats", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetMetaDetail(accountId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_meta_detail", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserAchievements(accountId: string, userId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_achievements", { accountId, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserNotesFiltered(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_notes_filtered", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserFeaturedNotes(accountId: string, userId: string, limit: number | null, untilId: string | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_featured_notes", { accountId, userId, limit, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetPages(accountId: string, endpoint: string, limit: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_pages", { accountId, endpoint, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetPage(accountId: string, pageId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_page", { accountId, pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiLikePage(accountId: string, pageId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_like_page", { accountId, pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnlikePage(accountId: string, pageId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unlike_page", { accountId, pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetGalleryPosts(accountId: string, limit: number | null, untilId: string | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_gallery_posts", { accountId, limit, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiLikeGalleryPost(accountId: string, postId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_like_gallery_post", { accountId, postId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnlikeGalleryPost(accountId: string, postId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unlike_gallery_post", { accountId, postId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFlashes(accountId: string, endpoint: string, limit: number | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_flashes", { accountId, endpoint, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFlash(accountId: string, flashId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_flash", { accountId, flashId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiLikeFlash(accountId: string, flashId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_like_flash", { accountId, flashId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnlikeFlash(accountId: string, flashId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unlike_flash", { accountId, flashId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiRequest(accountId: string, endpoint: string, params: JsonValue | null) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_request", { accountId, endpoint, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsUserNotes(accountId: string, params: JsonValue) : Promise<Result<UserNotesChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_user_notes", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsUserFollowing(accountId: string, params: JsonValue) : Promise<Result<UserFollowingChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_user_following", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsUserPv(accountId: string, params: JsonValue) : Promise<Result<UserPvChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_user_pv", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsActiveUsers(accountId: string, params: JsonValue) : Promise<Result<ActiveUsersChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_active_users", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsNotes(accountId: string, params: JsonValue) : Promise<Result<ServerNotesChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_notes", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsUsers(accountId: string, params: JsonValue) : Promise<Result<ServerUsersChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_users", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsFederation(accountId: string, params: JsonValue) : Promise<Result<FederationChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_federation", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsApRequest(accountId: string, params: JsonValue) : Promise<Result<ApRequestChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_ap_request", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiChartsDrive(accountId: string, params: JsonValue) : Promise<Result<ServerDriveChart, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_charts_drive", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFederationInstances(accountId: string, params: JsonValue) : Promise<Result<FederationInstance[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_federation_instances", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetFederationInstance(accountId: string, params: JsonValue) : Promise<Result<FederationInstance, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_federation_instance", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetDrafts(accountId: string, params: JsonValue) : Promise<Result<NoteDraft[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_drafts", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateDraft(accountId: string, params: JsonValue) : Promise<Result<NoteDraft, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_draft", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUpdateDraft(accountId: string, params: JsonValue) : Promise<Result<NoteDraft, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_update_draft", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiDeleteDraft(accountId: string, params: JsonValue) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_delete_draft", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetClip(accountId: string, params: JsonValue) : Promise<Result<Clip, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_clip", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetMyFavoriteClips(accountId: string, params: JsonValue) : Promise<Result<Clip[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_my_favorite_clips", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateClip(accountId: string, params: JsonValue) : Promise<Result<Clip, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_clip", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiFavoriteClip(accountId: string, params: JsonValue) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_favorite_clip", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnfavoriteClip(accountId: string, params: JsonValue) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unfavorite_clip", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserClips(accountId: string, params: JsonValue) : Promise<Result<Clip[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_clips", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUpdatePage(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_update_page", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUpdateFlash(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_update_flash", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetNoteRaw(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_note_raw", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetDriveFile(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_drive_file", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserRaw(accountId: string, params: JsonValue) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_raw", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserReactions(accountId: string, params: JsonValue) : Promise<Result<UserReaction[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_reactions", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserPagesBy(accountId: string, params: JsonValue) : Promise<Result<Page[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_pages_by", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserFlashs(accountId: string, params: JsonValue) : Promise<Result<Flash[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_flashs", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserGalleryBy(accountId: string, params: JsonValue) : Promise<Result<GalleryPost[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_gallery_by", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetList(accountId: string, params: JsonValue) : Promise<Result<UserList, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_list", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetUserListsBy(accountId: string, params: JsonValue) : Promise<Result<UserList[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_user_lists_by", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiFavoriteList(accountId: string, params: JsonValue) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_favorite_list", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiUnfavoriteList(accountId: string, params: JsonValue) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_unfavorite_list", { accountId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiFetchAccountTheme(accountId: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_fetch_account_theme", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetChatHistory(accountId: string, limit: number | null, room: boolean | null) : Promise<Result<ChatMessage[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_chat_history", { accountId, limit, room }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetChatUserMessages(accountId: string, userId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<ChatMessage[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_chat_user_messages", { accountId, userId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiGetChatRoomMessages(accountId: string, roomId: string, limit: number | null, sinceId: string | null, untilId: string | null) : Promise<Result<ChatMessage[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_get_chat_room_messages", { accountId, roomId, limit, sinceId, untilId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiCreateChatMessage(accountId: string, userId: string | null, roomId: string | null, text: string) : Promise<Result<ChatMessage, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_create_chat_message", { accountId, userId, roomId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authStart(host: string, permissions: string[] | null) : Promise<Result<AuthSession, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_start", { host, permissions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authCompleteAndSave(session: AuthSession, software: string) : Promise<Result<AccountPublic, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_complete_and_save", { session, software }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamConnect(accountId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_connect", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamDisconnect(accountId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_disconnect", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch between realtime (WebSocket) and polling (HTTP) mode.
 * Subscriptions are preserved across the switch.
 */
async streamSetMode(accountId: string, mode: string, intervalMs: number | null) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_set_mode", { accountId, mode, intervalMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect + subscribe in a single IPC round-trip (timeline).
 */
async streamConnectAndSubscribeTimeline(accountId: string, timelineType: TimelineType, listId: string | null) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_connect_and_subscribe_timeline", { accountId, timelineType, listId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect + subscribe in a single IPC round-trip (antenna).
 */
async streamConnectAndSubscribeAntenna(accountId: string, antennaId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_connect_and_subscribe_antenna", { accountId, antennaId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect + subscribe in a single IPC round-trip (channel).
 */
async streamConnectAndSubscribeChannel(accountId: string, channelId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_connect_and_subscribe_channel", { accountId, channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect + subscribe in a single IPC round-trip (role timeline).
 */
async streamConnectAndSubscribeRole(accountId: string, roleId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_connect_and_subscribe_role", { accountId, roleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeTimeline(accountId: string, timelineType: TimelineType, listId: string | null) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_timeline", { accountId, timelineType, listId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeAntenna(accountId: string, antennaId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_antenna", { accountId, antennaId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeChannel(accountId: string, channelId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_channel", { accountId, channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeRole(accountId: string, roleId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_role", { accountId, roleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeChatUser(accountId: string, otherId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_chat_user", { accountId, otherId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeChatRoom(accountId: string, roomId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_chat_room", { accountId, roomId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubscribeMain(accountId: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_subscribe_main", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamUnsubscribe(accountId: string, subscriptionId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_unsubscribe", { accountId, subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamSubNote(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_sub_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamUnsubNote(accountId: string, noteId: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_unsub_note", { accountId, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchOgp(url: string, accountId: string | null) : Promise<Result<SummaryData, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_ogp", { url, accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchNodeinfo(host: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_nodeinfo", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchServerMeta(host: string) : Promise<Result<JsonValue, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_server_meta", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchImageBase64(url: string) : Promise<Result<string | null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_image_base64", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkEndpointHealth(url: string, bearerToken: string | null) : Promise<Result<HealthCheckResult, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_endpoint_health", { url, bearerToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCliCommands() : Promise<CliCommandInfo[]> {
    return await TAURI_INVOKE("get_cli_commands");
},
async getRustcVersion() : Promise<string> {
    return await TAURI_INVOKE("get_rustc_version");
},
async getOpenapiSpec() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_openapi_spec");
},
async openDevtools() : Promise<void> {
    await TAURI_INVOKE("open_devtools");
},
/**
 * Export notecli.db to a user-chosen location via save dialog.
 */
async exportDb() : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import notecli.db from a user-chosen file via open dialog.
 * Replaces the current database file. Caller should relaunch the app afterwards
 * so that Rust re-opens the new DB with a fresh connection.
 */
async importDb() : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download an image from URL and save to a user-chosen location via save dialog.
 */
async saveImageToFile(url: string) : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_image_to_file", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List files in a settings subdirectory.
 */
async listSettingsFiles(subdir: string) : Promise<Result<string[], { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_settings_files", { subdir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a settings file as a UTF-8 string.
 */
async readSettingsFile(subdir: string, name: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_settings_file", { subdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a settings file (creates parent directories if needed).
 */
async writeSettingsFile(subdir: string, name: string, content: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_settings_file", { subdir, name, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a settings file.
 */
async deleteSettingsFile(subdir: string, name: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_settings_file", { subdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a settings file within the same subdirectory.
 */
async renameSettingsFile(subdir: string, oldName: string, newName: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_settings_file", { subdir, oldName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the settings directory path (so users can open it in file manager).
 */
async getSettingsDir() : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a settings file in the OS default editor. WSL2 では xdg-open が GUI
 * エディタへルーティングできないため、wslpath で Windows パスへ変換し
 * cmd.exe start 経由で Windows 側の既定アプリに委譲する。
 */
async openSettingsFileInEditor(subdir: string | null, name: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_settings_file_in_editor", { subdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a root-level settings file as a UTF-8 string.
 */
async readRootSettingsFile(name: string) : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_root_settings_file", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a root-level settings file.
 */
async writeRootSettingsFile(name: string, content: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_root_settings_file", { name, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read `settings.json5` (VSCode `settings.json` equivalent — single source of truth
 * for scalar preferences). Returns empty string if the file does not exist (first run).
 * 
 * Note: The Tauri command name stays `read_notedeck_json` for backwards-compatible
 * bindings. The file on disk is `settings.json5` to avoid collision with the export
 * bundle filename `notedeck.json`.
 */
async readNotedeckJson() : Promise<Result<string, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_notedeck_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write `settings.json5`. Creates the settings directory if missing.
 */
async writeNotedeckJson(content: string) : Promise<Result<null, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_notedeck_json", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export all settings files to a JSON bundle via save dialog.
 */
async exportSettingsJson() : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_settings_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import settings from a JSON bundle via open dialog.
 */
async importSettingsJson() : Promise<Result<boolean, { code: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_settings_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update performance config at runtime.
 */
async updatePerformanceConfig(config: PerformanceConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_performance_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get current performance config.
 */
async getPerformanceConfig() : Promise<Result<PerformanceConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_performance_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Token を含まない、フロントエンド向け Account 構造体
 */
export type AccountPublic = { id: string; host: string; userId: string; username: string; displayName: string | null; avatarUrl: string | null; software: string; hasToken: boolean }
/**
 * `charts/active-users`
 */
export type ActiveUsersChart = { readWrite: number[]; read: number[]; write: number[]; registeredWithinWeek: number[]; registeredWithinMonth: number[]; registeredWithinYear: number[]; registeredOutsideWeek: number[]; registeredOutsideMonth: number[]; registeredOutsideYear: number[] }
export type Antenna = { id: string; name: string }
/**
 * `charts/ap-request` (ActivityPub の配送成功/失敗/受信数)
 */
export type ApRequestChart = { deliverSucceeded: number[]; deliverFailed: number[]; inboxReceived: number[] }
export type AuthSession = { sessionId: string; url: string; host: string }
export type AvatarDecoration = { id: string; url: string; angle?: number | null; flipH?: boolean | null; offsetX?: number | null; offsetY?: number | null }
export type CacheStats = { note_count: number; db_size_bytes: number }
export type Channel = { id: string; name: string; color?: string | null }
export type ChatMessage = { id: string; createdAt: string; fromUserId: string; fromUser: ChatUser | null; toUserId: string | null; toUser: ChatUser | null; toRoomId: string | null; toRoom: ChatRoom | null; text: string | null; fileId: string | null; file: NormalizedDriveFile | null; isRead: boolean | null; reactions?: ChatMessageReaction[] }
export type ChatMessageReaction = { user: ChatReactionUser | null; reaction: string }
export type ChatReactionUser = { id: string; name: string | null; username: string; host: string | null; avatarUrl: string | null }
export type ChatRoom = { id: string; name: string | null; description: string | null }
export type ChatUser = { id: string; name: string | null; username: string; host: string | null; avatarUrl: string | null; emojis?: Partial<{ [key in string]: string }> }
/**
 * Metadata for a single CLI argument.
 */
export type CliArgInfo = { name: string; help: string | null; required: boolean; default_value: string | null }
/**
 * Metadata for a CLI subcommand (exposed to external consumers like notedeck).
 */
export type CliCommandInfo = { name: string; about: string | null; args: CliArgInfo[] }
/**
 * Misskey `clips/*` (clips/list, clips/show, clips/create, users/clips,
 * clips/my-favorites) の共通レスポンス。本家 schema
 * (packages/backend/src/models/json-schema/clip.ts) に準拠。
 */
export type Clip = { id: string; createdAt: string; lastClippedAt: string | null; userId: string; user: NormalizedUser; name: string; description: string | null; isPublic: boolean; favoritedCount: number; 
/**
 * `isFavorited` はログイン時のみサーバーから返る。
 */
isFavorited?: boolean | null; 
/**
 * `notesCount` は一部エンドポイントのみ返る。
 */
notesCount?: number | null }
export type CreateNoteParams = { text: string | null; cw: string | null; visibility: string | null; localOnly: boolean | null; modeFlags: Partial<{ [key in string]: boolean }> | null; replyId: string | null; renoteId: string | null; fileIds: string[] | null; poll: CreateNotePoll | null; scheduledAt: string | null }
export type CreateNotePoll = { choices: string[]; multiple: boolean | null; expiresAt: number | null }
/**
 * `charts/federation`
 */
export type FederationChart = { deliveredInstances: number[]; inboxInstances: number[]; stalled: number[]; sub: number[]; 
/**
 * `pub` は Rust 予約語。サーバーの JSON キーは "pub"。
 */
pub: number[]; pubsub: number[]; subActive: number[]; pubActive: number[] }
/**
 * Misskey `federation/instances` / `federation/show-instance` の 1 件分。
 * 本家 schema (packages/backend/src/models/Instance.ts) に準拠。
 * `show-instance` でのみ返るフィールドは Option にする。
 */
export type FederationInstance = { id: string; host: string; usersCount: number; notesCount: number; followingCount: number; followersCount: number; isNotResponding: boolean; isSuspended: boolean; isBlocked: boolean | null; isSilenced: boolean | null; isMediaSilenced: boolean | null; suspensionState: string | null; moderationNote: string | null; softwareName: string | null; softwareVersion: string | null; openRegistrations: boolean | null; name: string | null; description: string | null; maintainerName: string | null; maintainerEmail: string | null; iconUrl: string | null; faviconUrl: string | null; themeColor: string | null; firstRetrievedAt: string; infoUpdatedAt: string | null; latestRequestSentAt: string | null; latestRequestReceivedAt: string | null; latestStatus: number | null }
/**
 * `users/flashs` / `flash/show` の 1 件分。本家
 * packages/backend/src/models/Flash.ts。
 */
export type Flash = { id: string; createdAt: string; updatedAt: string; title: string; summary: string; script: string; userId: string; user?: NormalizedUser | null; permissions?: string[]; likedCount?: number | null; isLiked?: boolean | null }
export type FollowChartGroup = { inc: number[]; dec: number[]; total: number[] }
export type FollowChartSection = { followings: FollowChartGroup; followers: FollowChartGroup }
/**
 * `users/gallery/posts` / `gallery/posts/show` の 1 件分。本家
 * packages/backend/src/models/GalleryPost.ts。
 */
export type GalleryPost = { id: string; createdAt: string; updatedAt: string; title: string; description: string | null; userId: string; user?: NormalizedUser | null; files: NormalizedDriveFile[]; isSensitive?: boolean; likedCount?: number; isLiked?: boolean | null }
export type HealthCheckResult = { ok: boolean; status: number; message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type NormalizedDriveFile = { id: string; name: string; type: string; url: string; thumbnailUrl: string | null; size?: number; isSensitive?: boolean }
export type NormalizedNote = { id: string; _accountId: string; _serverHost: string; createdAt: string; text: string | null; cw: string | null; user: NormalizedUser; visibility: string; emojis?: Partial<{ [key in string]: string }>; reactionEmojis?: Partial<{ [key in string]: string }>; reactions?: Partial<{ [key in string]: number }>; myReaction: string | null; renoteCount: number; repliesCount: number; files?: NormalizedDriveFile[]; poll?: NormalizedPoll | null; replyId?: string | null; renoteId?: string | null; channelId?: string | null; channel?: Channel | null; reactionAcceptance?: string | null; uri?: string | null; url?: string | null; updatedAt?: string | null; localOnly?: boolean; visibleUserIds?: string[]; isFavorited?: boolean; 
/**
 * Fork-specific mode flags (e.g., isNoteInYamiMode)
 */
modeFlags: Partial<{ [key in string]: boolean }>; reply?: JsonValue | null; renote?: JsonValue | null }
export type NormalizedNoteReaction = { id: string; createdAt: string; user: NormalizedUser; type: string }
export type NormalizedNotification = { id: string; _accountId: string; _serverHost: string; createdAt: string; type: string; user: NormalizedUser | null; note: NormalizedNote | null; reaction: string | null; message?: string | null; achievement?: string | null; 
/**
 * Grouped reactions (for reaction:grouped type)
 */
reactions?: ReactionInfo[] | null; 
/**
 * Grouped users (for renote:grouped type)
 */
users?: NormalizedUser[] | null }
export type NormalizedPoll = { choices: NormalizedPollChoice[]; multiple?: boolean; expiresAt: string | null }
export type NormalizedPollChoice = { text: string; votes?: number; isVoted?: boolean }
export type NormalizedUser = { id: string; username: string; host: string | null; name: string | null; avatarUrl: string | null; isBot?: boolean; isCat?: boolean; avatarDecorations?: AvatarDecoration[]; emojis?: Partial<{ [key in string]: string }>; instance?: UserInstance | null }
export type NormalizedUserDetail = { id: string; username: string; host: string | null; name: string | null; avatarUrl: string | null; bannerUrl: string | null; description: string | null; followersCount?: number; followingCount?: number; notesCount?: number; isBot?: boolean; isCat?: boolean; isFollowing?: boolean; isFollowed?: boolean; createdAt?: string; avatarDecorations?: AvatarDecoration[]; emojis?: Partial<{ [key in string]: string }>; roles?: UserRole[]; fields?: UserField[]; url?: string | null; birthday?: string | null; location?: string | null; onlineStatus?: string | null; followingVisibility?: string | null; followersVisibility?: string | null }
export type NoteDraft = { id: string; createdAt: string; text: string | null; cw: string | null; visibility: string; localOnly?: boolean; fileIds?: string[]; hashtag?: string | null; replyId?: string | null; renoteId?: string | null; channelId?: string | null; poll?: NoteDraftPoll | null; scheduledAt?: number | null; isActuallyScheduled?: boolean }
/**
 * Misskey `notes/drafts/*` (2025.6+) のレスポンス。`notes/drafts/list` は
 * `Vec<NoteDraft>`、`notes/drafts/create` は `{ createdDraft: NoteDraft }`、
 * `notes/drafts/update` は `{ updatedDraft: NoteDraft }` を返す
 * (notedeck 側でラッパーを剥がして直接 NoteDraft を渡す)。
 */
export type NoteDraftPoll = { choices: string[]; multiple?: boolean | null; expiresAt?: number | null }
/**
 * `users/pages` / `pages/show` の 1 件分。本家 packages/backend/src/models/Page.ts。
 * プロフィール一覧で使うのは title / summary / createdAt のみだが、
 * `pages/show` でも同型を使えるようフルセットで定義。
 */
export type Page = { id: string; createdAt: string; updatedAt: string; title: string; name: string; summary: string | null; userId: string; user?: NormalizedUser | null; 
/**
 * `content` / `variables` はブロック構造で複雑。生 JSON で運ぶ。
 */
content?: JsonValue | null; variables?: JsonValue | null; script?: string | null; alignCenter?: boolean; hideTitleWhenPinned?: boolean; font?: string | null; eyeCatchingImageId?: string | null; eyeCatchingImage?: NormalizedDriveFile | null; likedCount?: number | null; isLiked?: boolean | null }
/**
 * Performance configuration shared across the application.
 * All fields are dynamically updatable at runtime via Tauri commands.
 */
export type PerformanceConfig = { memory_cache_max_total: number; memory_cache_max_item: number; max_concurrent_fetches: number; rust_ogp_cache_max: number; max_requests_per_window: number; circuit_breaker_threshold: number; circuit_breaker_duration: number; image_cache_ttl_days: number }
export type Player = { url: string; width: number | null; height: number | null; allow?: string[] }
export type PvChartGroup = { user: number[]; visitor: number[] }
export type ReactionInfo = { user: NormalizedUser; reaction: string }
export type SearchOptions = { limit?: number; sinceId: string | null; untilId: string | null; sinceDate: number | null; untilDate: number | null }
/**
 * `charts/drive` (Size は KB 単位)
 */
export type ServerDriveChart = { local: ServerDriveChartSection; remote: ServerDriveChartSection }
export type ServerDriveChartSection = { incCount: number[]; incSize: number[]; decCount: number[]; decSize: number[] }
/**
 * Emoji info exposed to the frontend via Tauri commands.
 */
export type ServerEmoji = { name: string; url: string; category: string | null; aliases: string[] }
/**
 * `charts/notes`
 */
export type ServerNotesChart = { local: ServerNotesChartSection; remote: ServerNotesChartSection }
export type ServerNotesChartSection = { total: number[]; inc: number[]; dec: number[]; diffs: UserNotesChartDiffs }
/**
 * `charts/users`
 */
export type ServerUsersChart = { local: ServerUsersChartSection; remote: ServerUsersChartSection }
export type ServerUsersChartSection = { total: number[]; inc: number[]; dec: number[] }
export type StoredServer = { host: string; software: string; version: string; featuresJson: string; updatedAt: number }
export type SummaryData = { title: string | null; description: string | null; icon: string | null; sitename: string | null; thumbnail: string | null; medias: string[]; player: Player | null; url: string; sensitive: boolean }
export type TimelineFilter = { withRenotes: boolean | null; withReplies: boolean | null; withFiles: boolean | null; withBots: boolean | null; withSensitive: boolean | null }
export type TimelineOptions = { limit?: number; sinceId: string | null; untilId: string | null; filters?: TimelineFilter | null; listId: string | null }
export type TimelineType = string
export type UserField = { name: string; value: string }
/**
 * `charts/user/following`
 */
export type UserFollowingChart = { local: FollowChartSection; remote: FollowChartSection }
export type UserInstance = { name: string | null; faviconUrl: string | null; iconUrl: string | null; themeColor: string | null }
/**
 * Misskey `users/lists/*` (list, show) の共通レスポンス。本家 schema
 * (packages/backend/src/models/json-schema/user-list.ts) に準拠。
 * 
 * `forPublic=true` で他人の公開リストを取得した時のみ `isLiked` /
 * `likedCount` が付加される (Clips の `isFavorited` / `favoritedCount` と
 * 非対称な命名は本家準拠)。
 */
export type UserList = { id: string; name: string; isPublic: boolean; createdAt?: string | null; userId?: string | null; userIds?: string[] | null; isLiked?: boolean | null; likedCount?: number | null }
/**
 * `charts/user/notes`
 */
export type UserNotesChart = { inc: number[]; dec: number[]; diffs: UserNotesChartDiffs }
export type UserNotesChartDiffs = { normal: number[]; reply: number[]; renote: number[]; withFile: number[] }
/**
 * `charts/user/pv` (pv = Natural PV、upv = Unique PV)
 */
export type UserPvChart = { pv: PvChartGroup; upv: PvChartGroup }
/**
 * `users/reactions` の 1 件分。自分のプロフィールで「リアクション」タブを
 * 開いたときに、自分が付けたリアクションとその対象 note を一覧する。
 */
export type UserReaction = { id: string; createdAt: string; 
/**
 * `type` は Rust 予約語。サーバーの JSON キーは "type"。
 */
type: string; note: NormalizedNote }
export type UserRole = { id: string; name: string; color: string | null; iconUrl: string | null; description: string | null; displayOrder?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
